### ISSUE TITLE
Highlight errors when nesting

### ISSUE THREAD

**Issue by yisibl** [hudochenkov/Syntax-highlighting-for-PostCSS#5]
``` css
body {
  padding: calc((var(--fontSize) / 2) + 1px);
  font-size: calc(var(--fontSize) * 1.2);
}
```

![](http://gtms01.alicdn.com/tps/i1/TB1BnzJKpXXXXXiaXXXt.NwZXXX-530-109.png)
